- name: variables
  hosts: local
  connection: local
  vars:
    Course: "devops with aws"
    trainer: "siva"
    duration: "120 hrs"

  tasks: #variables
   - name: print the variables
     ansible.builtin.debug:
      msg: "course is {{Course}},trainer is {{trainer}} and duration is {{duration}}"