- name: variables
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter Course name
    - name: TRAINER
      prompt: please enter trainer name
    - name: Duration
      prompt: please enter duration
  tasks: #variables
   - name: print the variables
     ansible.builtin.debug:
      msg: "COURSE is {{Course}},TRAINER is {{trainer}} and Duration is {{duration}}"