- name: variables
  hosts: local
  connection: local 
  tasks: #variables
   - name: print the variables
     ansible.builtin.debug:
      msg: "course is {{COURSE}},trainer is {{TRAINER}} and duration is {{DURATION}}"